resources:
  - url: http://127.0.0.1:5000/nissan-leaf-card.js
    type: module
views:
  - cards:
      - type: custom:nissan-leaf-card
        name: Nissan Leaf Card Development
        entity: sun.sun
        test_gui: true
